version: '3'

services:
  mock_api:
    build:
      context: ./src
      dockerfile: Dockerfile_mock
    image: snack_mock_api:latest
    ports:
      - 9001:9001
    environment:
      - FLASK_ENV=development

  api:
    build:
      context: ./src
      dockerfile: Dockerfile
    image: snack_api:latest
    ports:
      - 9002:9001
    env_file:
      - variables.env
