FROM python:3.7-slim

ENV PYTHONUNBUFFERED 1

# upgrade pip to the latest version.
RUN pip install --upgrade pip

# Set the working directory to /code/
WORKDIR /code/

COPY mock_api/requirements.txt requirements.txt
RUN pip install -r requirements.txt

COPY core core/
COPY mock_api/app.py mock_api/app.py

CMD ["gunicorn", "mock_api.app:app", "-b 0.0.0.0:9001", "-t 300"]
