version: '3'

services:
  mock_api:
    build:
      context: .
      dockerfile: Dockerfile_mock
    image: snack_mock_api:latest
    ports:
      - 9001:9001
    environment:
      - FLASK_ENV=development

  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: snack_api:latest
    ports:
      - 9002:9001
    environment:
      - FLASK_ENV=development
      - PROCESSING_API_HOST=http://interview-api.snackable.ai
      - MAX_PAGES=200