name: PR build.

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo.
        uses: actions/checkout@v2
      - name: List all files.
        run: |
          ls -al
      - name: Docker build.
        run: docker-compose build api
      - name: Run flake8.
        run: docker-compose run --rm api flake8 .
      - name: Run unittest.
        run: docker-compose run --rm api python -m unittest
